package com.aichat.assistant.presentation.chat

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.aichat.assistant.domain.model.ApiProviderSettings
import com.aichat.assistant.domain.model.AppError
import com.aichat.assistant.domain.model.ChatPreferences
import com.aichat.assistant.domain.model.Message
import com.aichat.assistant.domain.model.MessageStatus
import com.aichat.assistant.domain.model.Sender
import com.aichat.assistant.domain.repository.ConversationRepository
import com.aichat.assistant.domain.repository.Outcome
import com.aichat.assistant.domain.repository.SettingsRepository
import com.aichat.assistant.domain.usecase.SendMessageUseCase
import com.aichat.assistant.utils.logIfDebug
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

data class ChatUiState(
    val conversationTitle: String = "",
    val modelName: String = "",
    val messages: List<Message> = emptyList(),
    val inputText: String = "",
    val isBusy: Boolean = false,
    val markdownEnabled: Boolean = true,
    val sendWithEnter: Boolean = false
)

/**
 * One conversation's worth of state. [conversationId] is generated by the caller (Home's "New
 * Chat" button or a History row) before this ViewModel is created, so navigation routes stay
 * stable; the Room row itself is only written on the first successful send, so aborted empty
 * chats never clutter history.
 */
class ChatViewModel(
    private val conversationId: String,
    private val conversationRepository: ConversationRepository,
    private val settingsRepository: SettingsRepository,
    private val sendMessageUseCase: SendMessageUseCase
) : ViewModel() {

    private val inputText = MutableStateFlow("")
    private var currentSettings: ApiProviderSettings = ApiProviderSettings()
    private var currentPreferences: ChatPreferences = ChatPreferences()
    private var conversationPersisted = false
    private var generationJob: Job? = null

    val uiState: StateFlow<ChatUiState> = combine(
        conversationRepository.observeMessages(conversationId),
        inputText,
        settingsRepository.providerSettings,
        settingsRepository.chatPreferences
    ) { messages, input, settings, preferences ->
        currentSettings = settings
        currentPreferences = preferences
        ChatUiState(
            conversationTitle = titleFromMessages(messages),
            modelName = settings.model,
            messages = messages,
            inputText = input,
            isBusy = messages.any { it.status == MessageStatus.SENDING || it.status == MessageStatus.STREAMING },
            markdownEnabled = preferences.markdownEnabled,
            sendWithEnter = preferences.sendWithEnter
        )
    }.stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), ChatUiState())

    private fun titleFromMessages(messages: List<Message>): String =
        messages.firstOrNull { it.sender == Sender.USER }?.content?.take(48) ?: ""

    fun onInputChange(text: String) {
        inputText.value = text
    }

    fun sendMessage() {
        val text = inputText.value.trim()
        if (text.isBlank() || generationJob?.isActive == true) return
        inputText.value = ""
        viewModelScope.launch {
            ensureConversationPersisted()
            val history = uiState.value.messages
            val userMessage = Message(conversationId = conversationId, sender = Sender.USER, content = text)
            conversationRepository.saveMessage(userMessage)
            runGeneration(history, text)
        }
    }

    fun stopGenerating() {
        generationJob?.cancel()
    }

    fun retry(messageId: String) {
        val messages = uiState.value.messages
        val index = messages.indexOfFirst { it.id == messageId }
        if (index <= 0) return
        val precedingUser = messages.getOrNull(index - 1) ?: return
        viewModelScope.launch {
            conversationRepository.deleteMessage(messageId)
            // history is everything strictly BEFORE the preceding user message — that message
            // itself is passed separately as the prompt, so it isn't duplicated in the request.
            runGeneration(messages.take(index - 1), precedingUser.content)
        }
    }

    fun regenerate(assistantMessageId: String) = retry(assistantMessageId)

    fun editMessage(messageId: String, newContent: String) {
        val messages = uiState.value.messages
        val index = messages.indexOfFirst { it.id == messageId }
        if (index == -1) return
        viewModelScope.launch {
            val edited = messages[index].copy(content = newContent)
            conversationRepository.updateMessage(edited)
            // Anything after the edited message is now stale — drop it and regenerate.
            messages.drop(index + 1).forEach { conversationRepository.deleteMessage(it.id) }
            // history is everything strictly BEFORE the edited message — its new content is
            // passed separately as the prompt, so it isn't duplicated in the request.
            runGeneration(messages.take(index), newContent)
        }
    }

    fun deleteMessage(messageId: String) {
        viewModelScope.launch { conversationRepository.deleteMessage(messageId) }
    }

    fun clearConversation() {
        viewModelScope.launch { conversationRepository.clearConversation(conversationId) }
    }

    fun togglePin() {
        viewModelScope.launch { conversationRepository.togglePin(conversationId) }
    }

    fun buildMarkdownExport(): String {
        val state = uiState.value
        return buildString {
            appendLine("# ${state.conversationTitle}")
            appendLine()
            state.messages.forEach { message ->
                val label = if (message.sender == Sender.USER) "**شما**" else "**دستیار**"
                appendLine(label)
                appendLine()
                appendLine(message.content)
                appendLine()
            }
        }
    }

    fun buildJsonExport(): String {
        val state = uiState.value
        val escaped = state.messages.joinToString(",\n") { message ->
            val content = message.content
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
            """    {"sender": "${message.sender.name}", "content": "$content"}"""
        }
        return "{\n  \"title\": \"${state.conversationTitle}\",\n  \"messages\": [\n$escaped\n  ]\n}"
    }

    private suspend fun ensureConversationPersisted() {
        if (conversationPersisted) return
        val existing = conversationRepository.getConversation(conversationId)
        if (existing == null) {
            conversationRepository.createConversation(id = conversationId, title = "", modelUsed = currentSettings.model)
        }
        conversationPersisted = true
    }

    private fun runGeneration(history: List<Message>, promptText: String) {
        val settings = currentSettings
        val placeholder = Message(
            conversationId = conversationId,
            sender = Sender.ASSISTANT,
            content = "",
            status = MessageStatus.STREAMING
        )
        generationJob = viewModelScope.launch {
            conversationRepository.saveMessage(placeholder)
            val builder = StringBuilder()
            var lastError: AppError? = null

            try {
                sendMessageUseCase(
                    settings = settings,
                    history = history.filter { it.status == MessageStatus.COMPLETE },
                    userMessage = promptText,
                    streaming = currentPreferences.streamingEnabled
                ).collect { outcome ->
                    when (outcome) {
                        is Outcome.Ok -> {
                            builder.append(outcome.value)
                            conversationRepository.updateMessage(
                                placeholder.copy(content = builder.toString(), status = MessageStatus.STREAMING)
                            )
                        }
                        is Outcome.Err -> {
                            lastError = outcome.error
                            outcome.error.logIfDebug("ChatViewModel")
                        }
                    }
                }
            } finally {
                // Runs even when stopGenerating() cancels this job — a manual stop should leave
                // the partial answer saved as COMPLETE, not stuck showing a typing indicator.
                withContext(kotlinx.coroutines.NonCancellable) {
                    val finalStatus = if (lastError != null && builder.isEmpty()) MessageStatus.ERROR else MessageStatus.COMPLETE
                    conversationRepository.updateMessage(
                        placeholder.copy(
                            content = builder.toString(),
                            status = finalStatus,
                            error = if (finalStatus == MessageStatus.ERROR) lastError else null
                        )
                    )
                }
            }
        }
    }
}
